config/routes.rb
Rails.application.routes.draw do
  root 'user#new'
  get '/new', to: 'user#new'
  post '/create', to: 'user#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def new
    @user = User.all
  end
=begin
=end

  def create
    user = User.new
    user.username = params["username"]
    user.email = params["email"]
    user.bio = params["bio"]
    user.save
  end

=begin
=end

=begin

  def create
    @user = User.new('username' => params[:username],
                        'email' => params[:email],
                          'bio' => params[:bio])
    @user.save
  end

=end

=begin
=end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forms</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user/create.html.erb
<h1>Thank you for these information</h1>
<a href="/new">Click here to say something else</a>

        <td><%= @user.username %></td>
        <td><%= @user.email %></td>
        <td><%= @user.bio %></td>

app/views/user/new.html.erb
<h1>Hello there, tell me a bit about you</h1>

<!--  VERSION FORM HTML -->


<form action="<%= create_path %>" method="POST">
  <input type="hidden" name="authenticity_token"
  value="<%= form_authenticity_token %>">

  <div class="form-group">
    <label for="exampleInputEmail1">Username</label>
    <input type="text" name="username" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter Username">
    <small id="emailHelp" class="form-text text-muted">We'll never share your username with anyone else.</small>
  </div>

  <div class="form-group">
    <label for="exampleInputEmail1">Email</label>
    <input type="text" name="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter Email">
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>

  <div class="form-group">
    <label for="exampleInputEmail1">Bio</label>
    <input type="text" name="bio" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter your Bio mamen">
    <small id="emailHelp" class="form-text text-muted">We'll never share your bio with anyone else</small>
  </div>

  <button type="submit" class="btn btn-primary">Submit</button>
</form>


<!--  VERSION FORM_TAG

<%= form_tag url_for(action: 'create'), method: "post" do %>

           <%= label_tag 'Username' %>
           <%= text_field_tag 'username' %>
           <br /> <br />

           <%= label_tag 'Email' %>
           <%= text_field_tag 'email'%>
           <br /> <br />

           <%= label_tag 'Bio' %>
           <%= text_area_tag 'bio' %>
           <br /> <br />

           <%= submit_tag "Submit" %>
       <% end %>
-->